[build]
  command = "npm run clean && npm run build"
  publish = "out"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"
  NEXT_PUBLIC_SITE_URL = "https://markirovka-hz.netlify.app"
  NEXT_DISABLE_OPTIMIZE_CSS = "true"
  # Отключаем кэширование для решения проблем со сборкой
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Удаляем редиректы, которые могут конфликтовать с Next.js
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

[functions]
  node_bundler = "esbuild" 